services:
  php:
    image: registry.peacefulcraft.net/xcom/development:latest
    working_dir: /usr/src/myapp
    command: ["sh", "scripts/start-dev-server.sh"]
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/myapp
    networks:
      - pcn-xcom-development
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: development
      MYSQL_DATABASE: xcom
      MYSQL_USER: xcom
      MYSQL_PASSWORD: xcom
    ports:
      - "3306:3306"
    networks:
      - pcn-xcom-development
  pma:
    image: phpmyadmin:5
    environment:
      PMA_HOST: mariadb
    ports:
      - "8082:80"
    networks:
      - pcn-xcom-development

networks:
  pcn-xcom-development:
    name: pcn-xcom-development